name: Build and push docker image to Docker Hub

on:
  push:
    branches:
        - 'main'
        - 'stage'
        - 'prod'
        - 'cicd-workflow'
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: jass-ai-2024/workflows@make-docker-image
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          cicd-github-token: ${{ secrets.CICD_GITHUB_TOKEN }}
